# Generated by Django 3.0.7 on 2020-06-30 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('cinema_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد سینما')),
                ('name', models.CharField(max_length=50, verbose_name='نام سینما')),
                ('city', models.CharField(default='اصفهان', max_length=40, verbose_name='شهر سینما')),
                ('phone', models.IntegerField(null=True, verbose_name='شماره تلفن سینما')),
                ('capacity', models.IntegerField(default=100, verbose_name='ظرفیت سینما')),
                ('address', models.TextField(verbose_name='آدرس سینما')),
            ],
            options={
                'verbose_name': 'سینما',
                'verbose_name_plural': 'سینماها',
            },
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'فیلم', 'verbose_name_plural': 'فیلم ها'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=50, verbose_name='کارگردان فیلم'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.IntegerField(default=120, verbose_name='زمان فیلم'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام فیلم'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=1380, verbose_name='سال ساخت فیلم'),
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='زمان سانس')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('sabale_seats', models.IntegerField(verbose_name='تعداد صندلی ها')),
                ('free_seats', models.IntegerField(verbose_name='تعداد صندلی خالی')),
                ('status', models.IntegerField(choices=[(1, 'فروش آغاز نشده'), (2, 'در حال فروش بلیط'), (3, 'بلیط ها تمام شد'), (4, 'فروش بلیط بسته شد'), (5, 'فیلم پخش شد'), (6, 'سانس لغو شد')])),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.Cinema', verbose_name='نام سینما')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.Movie', verbose_name='نام فیلم')),
            ],
            options={
                'verbose_name': 'سانس',
                'verbose_name_plural': 'سانس ها',
            },
        ),
    ]
