# Generated by Django 3.0.7 on 2020-07-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_auto_20200630_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='address',
            field=models.TextField(null=True, verbose_name='آدرس سینما'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
    ]
