# Generated by Django 3.0.10 on 2020-09-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_image_field_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='imageposter/', verbose_name='پوستر'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='status',
            field=models.IntegerField(choices=[(1, 'فروش آغاز نشده'), (2, 'در حال فروش بلیط'), (3, 'بلیط ها تمام شد'), (4, 'فروش بلیط بسته شد'), (5, 'فیلم پخش شد'), (6, 'سانس لغو شد')], verbose_name='وضعیت'),
        ),
    ]
